services:
  dozzle_apps_logs:
    container_name: dozzle_apps_logs
    image: ghcr.io/casse-boubou/dozzle-apps-logs:v1.0.0@sha256:8113d34cc1ba947477876e82f5201e81fa2cf0ae95ea8d331b1c005ad68819cd
    environment:
      - TZ=Etc/UTC
    volumes:
      - /path/to/fluent.conf:/fluentd/etc/fluent.conf:ro
      # - /path/to/firstfile.log:/logs/firstfile.log:ro 
      # - /path/to/secondfile.log:/logs/secondfile.log:ro
      # - ....
      # - /var/run/docker.sock:/var/run/docker.sock (optional)