ARG FLUENTD_BASE_IMAGE_VERSION="v1.16.11-1.0@sha256:4b28d3e1b86ada26de62b832a3d25471d569c2fc9f79380acc0a621b1f0a018b"
FROM fluent/fluentd:${FLUENTD_BASE_IMAGE_VERSION} AS runner
ARG CONTAINER_BUILD_VERSION
ENV CONTAINER_BUILD_VERSION=${CONTAINER_BUILD_VERSION}
USER 0
# Update index, install app, and clean up cache
RUN echo "Installing base packages" \
    && apk --update --no-cache add \
    tzdata=2025b-r0 \
    haproxy=2.8.16-r0 \
    nodejs=20.15.1-r0 \
    npm=10.2.5-r0

# For HAPROXY and NODE
ENV SOCKET_PATH=/var/run/fakeDocker.sock


####################
# FLUENTD
####################
RUN mkdir -p /fluentd/etc && rm /fluentd/etc/fluent.conf


####################
# HAPROXY
####################
COPY ./haproxy/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
EXPOSE 2376
ENV PROXY_PORT=":2376" \
    LOG_LEVEL=info \
    CONTAINERS=1 \
    PING=1 \
    VERSION=1 \
    EVENTS=1 \
    INFO=1




##################################
## DEV MODE
##################################
WORKDIR /DEV
CMD ["sleep", "infinity"]
